name: Ville Québec Collecte Add-on
version: "1.0.0"
slug: ville_qc_collecte_addon

description: "Collectes ordures/recyclage à Québec"
arch:
  - amd64
  - armv7
  - armhf
  - arm64

startup: application
boot: manual

options:
  address: "2352 Rue de l'Alliance"
  update_interval: 3600  # en secondes (ex: 1h)
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""

schema:
  address: str
  update_interval: int
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str

image: "local/ville_qc_collecte_addon:latest"
