# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Ville Quebec Collecte Add-on
version: "1.2.3"
slug: example
description: Ville Quebec Collecte Add-on
url: "https://github.com/Frazou1/ville_qc_collecte"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  address: "123 Patate"
  update_interval: 3600
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  # Chemin où sera généré le fichier ICS (ici dans le dossier "share" mappé en lecture/écriture)
  calendar_file: "/share/ville_qc_collecte.ics"
schema:
  address: str
  update_interval: int
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  calendar_file: str
build:
  builder: docker
  file: Dockerfile
