# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Ville Quebec Collecte Ordure
version: "1.2.0"
slug: example
description: Ville Quebec Collecte Ordure
url: "https://github.com/Frazou1/ville_qc_collecte"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
